spring:
  datasource:
   url: jdbc:msql://localhost/tamplate?createDatabaseIfNotExist=true&useSSL=false
   username: root
   password: root
   driven-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-startegy: org.hibernate.cfg.ImprovedNamingStrategy
  server:
   port: 8080
